#!/bin/bash
# vim: set ft=sh

set -e

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

TMPDIR=${TMPDIR:-/tmp}

destination=$1

if [ -z "$destination" ]; then
  echo "usage: $0 <path/to/destination>" >&2
  exit 1
fi

payload=$(mktemp "$TMPDIR/bosh-creds.XXXXXX")

cat > "$payload" <&0

pcf_opsman_admin_username=$(jq -r '.source.pcf_opsman_admin_username // ""' < $payload)
pcf_opsman_admin_password=$(jq -r '.source.pcf_opsman_admin_password // ""' < $payload)
opsman_url=$(jq -r '.source.opsman_url // ""' < $payload)

jumpbox_url=$(jq -r '.source.jumpbox_url // ""' < $payload)
jumpbox_port=$(jq -r '.source.jumpbox_port // 22' < $payload)
jumpbox_ssh_key=$(jq -r '.source.jumpbox_ssh_key // ""' < $payload)
jumpbox_ssh_key_escaped=$(jq '.source.jumpbox_ssh_key // ""' < $payload)
jumpbox_user=$(jq -r '.source.jumpbox_user // ""' < $payload)

CURL="om --target https://${opsman_url} -k \
  --username $pcf_opsman_admin_username \
  --password $pcf_opsman_admin_password \
  curl"

# Get user, pass and CA cert
CA_CERT=$($CURL --path=/api/v0/security/root_ca_certificate | jq -r .root_ca_certificate_pem)
echo "$CA_CERT" > "$destination/bosh-ca.pem"

$CURL --path=/api/v0/deployed/director/credentials/director_credentials > creds.json

jq -r .credential.value.identity < creds.json > "$destination/bosh-username"
jq -r .credential.value.password < creds.json > "$destination/bosh-pass"

BOSH_DEPLOYMENT=$(jq -r '.params.deployment // ""' < $payload)
echo "$BOSH_DEPLOYMENT" > "$destination/bosh-deployment"

# Get Director ip
director_id=$($CURL --path=/api/v0/deployed/products | jq -r ".[].guid" | grep p-bosh)

$CURL --path="/api/v0/deployed/products/$director_id/static_ips" | jq -r .[0].ips[0] > "$destination/director_ip"

# In PCF 1.12 there is a new endpoint with credentials to use with BOSH CLIv2
set +e
$CURL --path=/api/v0/deployed/director/credentials/bosh2_commandline_credentials > "$destination/bosh2_commandline_credentials.tmp"
# shellcheck disable=SC2181
if [[ "$?" = "0" ]]; then
  jq -r .credential < "$destination/bosh2_commandline_credentials.tmp" | awk '{printf "export %s\nexport %s\nexport %s\n", $1, $2, $4}' > "$destination/bosh2_commandline_credentials"
  {
    echo "export BOSH_CA_CERT=$'"
    cat "$destination/bosh-ca.pem"
    echo "'"
  } >> "$destination/bosh2_commandline_credentials"

  if [[ -n "${jumpbox_ssh_key}" ]]; then
    {
      echo 'jumpbox_ssh_key="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"/jumpbox.key'
      echo "echo $'$jumpbox_ssh_key' > \$jumpbox_ssh_key"
      echo 'chmod 600 $jumpbox_ssh_key'
      echo "export BOSH_ALL_PROXY=ssh+socks5://${jumpbox_user}@${jumpbox_url}:22?private-key=\$jumpbox_ssh_key"
    } >> "$destination/bosh2_commandline_credentials"
  fi

  # shellcheck disable=1090
  source "$destination/bosh2_commandline_credentials"

  CA_CERT=$($CURL --path=/api/v0/security/root_ca_certificate | jq .root_ca_certificate_pem)
  # [BOSH Deployment Resource](https://github.com/cloudfoundry/bosh-deployment-resource) supports dynamic configuration through a JSON file
  # Let's create such a file so that the resource can be used for deployment
  echo "{ \"target\": \"$BOSH_ENVIRONMENT\", \"client\": \"$BOSH_CLIENT\", \"client_secret\": \"$BOSH_CLIENT_SECRET\", \"ca_cert\": $CA_CERT, \"deployment\": \"$BOSH_DEPLOYMENT\", \"jumpbox_url\": \"$jumpbox_url:$jumpbox_port\", \"jumpbox_user\": \"$jumpbox_user\", \"jumpbox_ssh_key\": $jumpbox_ssh_key_escaped }" > "$destination/opsman_bosh.json"
fi
set -e

external_bosh_address=$(jq -r '.source.external_bosh_address // ""' < $payload)
if [[ ${external_bosh_address} ]]; then
  external_bosh_client=$(jq -r '.source.external_bosh_client // ""' < $payload)
  external_bosh_client_secret=$(jq -r '.source.external_bosh_client_secret // ""' < $payload)
  external_bosh_ca_cert=$(jq '.source.external_bosh_ca_cert // ""' < $payload)
  external_bosh_ca_cert_multiline=$(jq -r '.source.external_bosh_ca_cert // ""' < $payload)

  echo "{ \"target\": \"${external_bosh_address}\", \"client\": \"${external_bosh_client}\", \"client_secret\": \"${external_bosh_client_secret}\", \"ca_cert\": ${external_bosh_ca_cert}, \"deployment\": \"$BOSH_DEPLOYMENT\", \"jumpbox_url\": \"$jumpbox_url:$jumpbox_port\", \"jumpbox_user\": \"$jumpbox_user\", \"jumpbox_ssh_key\": $jumpbox_ssh_key_escaped }" > "$destination/external_bosh.json"

  {
    echo "export BOSH_ENVIRONMENT=${external_bosh_address}";
    echo "export BOSH_CLIENT=${external_bosh_client}";
    echo "export BOSH_CLIENT_SECRET=${external_bosh_client_secret}";
    echo "export BOSH_CA_CERT=\"${external_bosh_ca_cert_multiline}\"";
  } > "$destination/external_bosh.sh"
fi

# Create a YAML file that can be used as BOSH var file (also by bosh-deployment resource)
echo "bosh_url: " $(cat "$destination/director_ip") > "$destination/pcf_bosh_director.yml"
echo "bosh_ca_cert: |" >> "$destination/pcf_bosh_director.yml"
sed 's/^/  /g' < "$destination/bosh-ca.pem" >> "$destination/pcf_bosh_director.yml"

rm -f "$destination/bosh2_commandline_credentials.tmp"

echo '{"version": {"ref": "123"}}' >&3
